[book]
authors = ["Willams Sousa"]
language = "pt_BR"
multilingual = false
src = "src"
title = "Criptografia para Desenvolvedores Go"
[build]
build-dir = "docs"

[preprocessor.katex]
after = ["links"]

